package com.uriel.logpose.domain.learning

/**
 * Intelligent suggestion generated by THAMIS.
 */
data class Recommendation(
    val id: String,
    val text: String,
    val action: String,
    val state: RecommendationState = RecommendationState.NEW
)

enum class RecommendationState {
    NEW,
    ACCEPTED,
    REJECTED
}
